from typing import Dict, Any
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def generate_markdown_report(sector: str, analysis: Dict[str, Any]) -> str:
    """
    Generate a structured markdown report from the AI analysis.

    Args:
        sector: The analyzed sector name
        analysis: Dictionary containing analysis data from Gemini

    Returns:
        Formatted markdown string
    """
    try:
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        # Header with metadata
        header = f"""# Trade Opportunities Analysis - {sector.title()} Sector

**Generated on:** {now}  
**Data Sources:** {analysis.get('data_sources', 0)}  
**Analysis Method:** AI-Powered (Google Gemini)

---
"""

        # Main analysis content
        analysis_content = analysis.get('analysis', 'Analysis unavailable')

        # Footer with disclaimer
        footer = f"""

---

## Disclaimer

This report is generated by an AI system and should not be considered as financial advice. Market conditions can change rapidly, and past performance does not guarantee future results. Always conduct your own research and consult with qualified financial advisors before making investment decisions.

**Risk Warning:** Trading in stocks and securities involves substantial risk and is not suitable for all investors. You may lose money.
"""

        # Combine all parts
        report = header + analysis_content + footer

        logger.info(f"Generated markdown report for sector: {sector}, length: {len(report)} characters")
        return report

    except Exception as e:
        logger.error(f"Error generating markdown report for sector {sector}: {str(e)}")
        # Fallback report
        return f"""# Trade Opportunities Analysis - {sector.title()} Sector

**Generated on:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}  
**Status:** Error generating analysis

## Analysis Unavailable

Unable to generate analysis report due to technical issues.

## Next Steps

- Please try again later
- Contact support if the issue persists

---

**Disclaimer:** This is an auto-generated report. Not financial advice.
"""
