"""
Generate Word Document Report with Scraped Data and AI Analysis
Standalone script that scrapes market data, analyzes it with AI, and generates a detailed Word document.
"""

import asyncio
import logging
import sys
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE

# Import project modules
from core.data_collector import collect_market_data
from core.ai_analyzer import analyze_with_gemini
from config.config import settings

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def create_word_document(sector: str, market_data: list, analysis_result: dict, filename: str = None) -> str:
    """
    Create a detailed Word document with scraped data and AI analysis.

    Args:
        sector: The analyzed market sector
        market_data: List of market data from web scraping
        analysis_result: AI analysis results
        filename: Optional custom filename

    Returns:
        Path to the generated document
    """
    try:
        # Create document
        doc = Document()

        # Set document properties
        doc.core_properties.title = f"Trade Opportunities Analysis - {sector.title()} Sector"
        doc.core_properties.subject = f"Market Analysis and Trade Opportunities for {sector}"
        doc.core_properties.author = "AI Market Analyst"
        doc.core_properties.created = datetime.utcnow()

        # Add title
        title = doc.add_heading(f'Trade Opportunities Analysis - {sector.title()} Sector', 0)
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        # Add metadata table
        metadata_table = doc.add_table(rows=4, cols=2)
        metadata_table.style = 'Table Grid'

        # Fill metadata table
        metadata_rows = [
            ("Generated On", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")),
            ("Sector", sector.title()),
            ("Data Sources", str(len(market_data))),
            ("Analysis Method", "AI-Powered (Google Gemini)")
        ]

        for i, (label, value) in enumerate(metadata_rows):
            cells = metadata_table.rows[i].cells
            cells[0].text = label
            cells[0].paragraphs[0].runs[0].font.bold = True
            cells[1].text = value

        doc.add_paragraph()  # Spacer

        # Section 1: Scraped Market Data
        doc.add_heading('Section 1: Scraped Market Data', level=1)
        doc.add_paragraph(f"This report includes data scraped from {len(market_data)} web sources using DuckDuckGo search for the {sector} sector in India.")

        # Create data table
        if market_data:
            table = doc.add_table(rows=1, cols=4)
            table.style = 'Table Grid'

            # Table headers
            header_cells = table.rows[0].cells
            headers = ["Title", "URL", "Content Snippet", "Date"]
            for i, header in enumerate(headers):
                header_cells[i].text = header
                header_cells[i].paragraphs[0].runs[0].font.bold = True

            # Add data rows
            for i, item in enumerate(market_data, 1):
                row_cells = table.add_row().cells
                row_cells[0].text = item.get('title', 'N/A')[:100] + '...' if len(item.get('title', '')) > 100 else item.get('title', '')
                row_cells[1].text = item.get('url', 'N/A')
                row_cells[2].text = item.get('body', 'N/A')[:300] + '...' if len(item.get('body', '')) > 300 else item.get('body', '')
                row_cells[3].text = item.get('date', 'N/A')

        doc.add_paragraph()  # Spacer

        # Section 2: AI Analysis Results
        doc.add_heading('Section 2: AI Analysis Results', level=1)
        doc.add_paragraph("The following analysis was generated by Google Gemini AI based on the scraped market data.")

        # Add the analysis content
        analysis_content = analysis_result.get('analysis', 'Analysis unavailable')

        # Split analysis into paragraphs and add to document
        paragraphs = analysis_content.split('\n\n')
        for paragraph in paragraphs:
            # Skip empty paragraphs
            paragraph = paragraph.strip()
            if not paragraph:
                continue

            # Handle headers (lines starting with #)
            if paragraph.startswith('#'):
                lines = paragraph.split('\n')
                header_text = lines[0].lstrip('#').strip()
                level = min(paragraph.count('#'), 3)  # Max level 3 for Word

                doc.add_heading(header_text, level=level)

                # Add remaining content if any
                if len(lines) > 1:
                    doc.add_paragraph('\n'.join(lines[1:]))

            # Handle bullet points
            elif paragraph.strip().startswith('- ') or paragraph.strip().startswith('* '):
                lines = paragraph.split('\n')
                for line in lines:
                    if line.strip().startswith(('- ', '* ')):
                        p = doc.add_paragraph(line.strip()[2:], style='List Bullet')
                    else:
                        p = doc.add_paragraph(line.strip())

            # Regular paragraphs
            else:
                p = doc.add_paragraph(paragraph)

        # Add error note if present
        if analysis_result.get('error'):
            doc.add_paragraph()
            doc.add_paragraph("⚠️ Note: AI analysis encountered an error and this may be a fallback response.", style='Intense Quote')

        doc.add_paragraph()  # Spacer

        # Disclaimer section
        doc.add_heading('Important Disclaimer', level=2)
        disclaimer = doc.add_paragraph()
        disclaimer.add_run("This report is generated by an AI system and should not be considered as financial advice. Market conditions can change rapidly, and past performance does not guarantee future results. Always conduct your own research and consult with qualified financial advisors before making investment decisions.").italic = True

        risk_warning = doc.add_paragraph()
        risk_warning.add_run("Risk Warning: Trading in stocks and securities involves substantial risk and is not suitable for all investors. You may lose money.").bold = True

        # Generate filename
        if not filename:
            timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            filename = f"trade_analysis_{sector}_{timestamp}.docx"

        # Save document
        doc.save(filename)
        logger.info(f"Word document saved as: {filename}")

        return filename

    except Exception as e:
        logger.error(f"Error creating Word document: {str(e)}")
        raise


async def main(sector: str = "pharmaceuticals"):
    """
    Main function to generate the Word document report.

    Args:
        sector: Market sector to analyze (default: pharmaceuticals)
    """
    try:
        logger.info(f"Starting Word document generation for sector: {sector}")

        # Step 1: Scrape market data
        logger.info("Step 1: Scraping market data...")
        market_data = collect_market_data(sector)

        if not market_data:
            logger.warning("No market data scraped. Continuing with analysis anyway.")

        # Step 2: Analyze with AI
        logger.info("Step 2: Running AI analysis...")
        analysis_result = await analyze_with_gemini(sector, market_data)

        # Step 3: Generate Word document
        logger.info("Step 3: Generating Word document...")
        filename = create_word_document(sector, market_data, analysis_result)

        logger.info("✅ Word document generation completed successfully!")
        logger.info(f"Generated file: {filename}")

        return filename

    except Exception as e:
        logger.error(f"Error in main process: {str(e)}")
        raise


if __name__ == "__main__":
    # Get sector from command line argument or use default
    sector = sys.argv[1] if len(sys.argv) > 1 else "pharmaceuticals"

    print(f"Generating Word document report for sector: {sector}")
    print("=" * 60)

    # Run the async main function
    try:
        result_filename = asyncio.run(main(sector))
        print("=" * 60)
        print(f"✅ SUCCESS: Word document generated: {result_filename}")
        print("The document includes both scraped market data and AI analysis.")

    except Exception as e:
        print("=" * 60)
        print(f"❌ ERROR: {str(e)}")
        sys.exit(1)
